# Generated by Django 5.0.6 on 2024-07-03 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_answers_questions_userresponses'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='questions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.questions'),
        ),
        migrations.AddField(
            model_name='questions',
            name='risks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.risks'),
        ),
        migrations.AddField(
            model_name='userresponses',
            name='answers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.answers'),
        ),
        migrations.AddField(
            model_name='userresponses',
            name='questions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.questions'),
        ),
    ]
