# Generated by Django 5.0.6 on 2024-07-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_answers_questions_questions_risks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='prob_happen',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='prob_nothappen',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
